export default {
    FETCH_BUILDINGS_STARTED: 'FETCH_BUILDINGS_STARTED',
    FETCH_BUILDINGS_SUCCESS: 'FETCH_BUILDINGS_SUCCESS',
    FETCH_BUILDINGS_FAILURE: 'FETCH_BUILDINGS_FAILURE',
    FETCH_BUILDINGS_ENDED: 'FETCH_BUILDINGS_ENDED',

    FETCH_AREAS_STARTED: 'FETCH_AREAS_STARTED',
    FETCH_AREAS_SUCCESS: 'FETCH_AREAS_SUCCESS',
    FETCH_AREAS_FAILURE: 'FETCH_AREAS_FAILURE',
    FETCH_AREAS_ENDED: 'FETCH_AREAS_ENDED',

    FETCH_OPEN_HOUSES_STARTED: 'FETCH_OPEN_HOUSES_STARTED',
    FETCH_OPEN_HOUSES_SUCCESS: 'FETCH_OPEN_HOUSES_SUCCESS',
    FETCH_OPEN_HOUSES_FAILURE: 'FETCH_OPEN_HOUSES_FAILURE',
    FETCH_OPEN_HOUSES_ENDED: 'FETCH_OPEN_HOUSES_ENDED',

    FETCH_EVENTS_STARTED: 'FETCH_EVENTS_STARTED',
    FETCH_EVENTS_SUCCESS: 'FETCH_EVENTS_SUCCESS',
    FETCH_EVENTS_FAILURE: 'FETCH_EVENTS_FAILURE',
    FETCH_EVENTS_ENDED: 'FETCH_EVENTS_ENDED',

    FETCH_EATERIES_STARTED: 'FETCH_EATERIES_STARTED',
    FETCH_EATERIES_SUCCESS: 'FETCH_EATERIES_SUCCESS',
    FETCH_EATERIES_FAILURE: 'FETCH_EATERIES_FAILURE',
    FETCH_EATERIES_ENDED: 'FETCH_EATERIES_ENDED',

    ADD_EVENT_TO_PLANNER: 'ADD_EVENT_TO_PLANNER',
    REMOVE_EVENT_FROM_PLANNER: 'REMOVE_EVENT_FROM_PLANNER',

    HIDE_ERROR: 'HIDE_ERROR',
};
