name: Build

on: [push, pull_request]

jobs:
  build_android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        enviroment: [prod, test]
        include:
          - enviroment: prod
            backend: https://vlpl6d8t30.execute-api.us-east-1.amazonaws.com/Prod
            artifact_name: prod-env-build
          - enviroment: test
            backend: https://ld89hb8od1.execute-api.us-east-1.amazonaws.com/Prod
            artifact_name: test-env-build
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          path: ${{ format('{{0}.apk}', matrix.artifact_name)}}
      - name: Install Dependencies
        run: yarn install
      - name: Build Keystore
        run: |
          echo $EXPO_ANDROID_KEYSTORE_BASE64 > app.jks.base64
          base64 --decode app.jks.base64 > app.jks
        env:
          EXPO_ANDROID_KEYSTORE_BASE64: ${{ secrets.EXPO_ANDROID_KEYSTORE_BASE64 }}
      - name: Build
        run: yarn run build:android --keystore-path app.jks --keystore-alias $EXPO_ANDROID_KEYSTORE_ALIAS --type apk -o ~/$ARTIFACT_NAME.apk
        env:
          BACKEND_URL: ${{ matrix.backend }}
          EXPO_USERNAME: ${{ secrets.EXPO_USERNAME }}
          EXPO_PASSWORD: ${{ secrets.EXPO_PASSWORD }}
          EXPO_ANDROID_KEYSTORE_ALIAS: ${{ secrets.EXPO_ANDROID_KEYSTORE_ALIAS }}
          EXPO_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.EXPO_ANDROID_KEYSTORE_PASSWORD }}
          EXPO_ANDROID_KEY_PASSWORD: ${{ secrets.EXPO_ANDROID_KEY_PASSWORD }}
          ARTIFACT_NAME: ${{ matrix.artifact_name }}
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ format('{{{0}.apk}}', matrix.artifact_name)}}
