name: Build

on: [push, pull_request]

jobs:
  build_android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        enviroment: [prod, test]
        include:
          - enviroment: prod
            backend: https://vlpl6d8t30.execute-api.us-east-1.amazonaws.com/Prod
            artifact_name: prod-env-build
          - enviroment: test
            backend: https://ld89hb8od1.execute-api.us-east-1.amazonaws.com/Prod
            artifact_name: test-env-build
    steps:
      - uses: actions/checkout@v1
      - name: Setup kernel for react native, increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install Dependencies
        run: yarn install
      - name: Build Keystore
        run: |
          echo $EXPO_ANDROID_KEYSTORE_BASE64 > app.jks.base64
          base64 --decode app.jks.base64 > app.jks
        env:
          EXPO_ANDROID_KEYSTORE_BASE64: ${{ secrets.EXPO_ANDROID_KEYSTORE_BASE64 }}
      - name: Setup Environment Variables
        run: echo -e "BACKEND_URL=$BACKEND_URL" > .env.production
        env:
          BACKEND_URL: ${{ matrix.backend }}
      - name: Setup Google Maps api key
        run: sed "s/GOOGLE_MAPS_API_KEY_CHANGE_ME/$GOOGLE_MAPS_API_KEY/g" app.json > prod.app.json
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
      - name: Publish App
        run: |
          yarn run expo:login -u $EXPO_USERNAME -p $EXPO_PASSWORD --non-interactive
          yarn run expo:publish --config prod.app.json --release-channel $RELEASE_CHANNEL
        env:
          EXPO_USERNAME: ${{ secrets.EXPO_USERNAME }}
          EXPO_PASSWORD: ${{ secrets.EXPO_PASSWORD }}
          RELEASE_CHANNEL: ${{ format('{0}_{1}', matrix.enviroment, github.run_id) }}
      - name: Build
        run: yarn run build:android --keystore-path app.jks --keystore-alias $EXPO_ANDROID_KEYSTORE_ALIAS --type apk -o $ARTIFACT_NAME.apk --config prod.app.json --release-channel $RELEASE_CHANNEL
        env:
          EXPO_USERNAME: ${{ secrets.EXPO_USERNAME }}
          EXPO_PASSWORD: ${{ secrets.EXPO_PASSWORD }}
          EXPO_ANDROID_KEYSTORE_ALIAS: ${{ secrets.EXPO_ANDROID_KEYSTORE_ALIAS }}
          EXPO_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.EXPO_ANDROID_KEYSTORE_PASSWORD }}
          EXPO_ANDROID_KEY_PASSWORD: ${{ secrets.EXPO_ANDROID_KEY_PASSWORD }}
          ARTIFACT_NAME: ${{ matrix.artifact_name }}
          RELEASE_CHANNEL: ${{ format('{0}_{1}', matrix.enviroment, github.run_id) }}
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ format('{0}.apk', matrix.artifact_name) }}
